# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Kl6g24icOo5T8Ow6Tuh-TCfS83-WiUX
"""

!pip install langchain langchain-community langchain-google-genai

import os
# google AI studio
os.environ["GOOGLE_API_KEY"]="AQ.Ab8RN6IiY4QdpoDjc-YkCdiZLYFnW9Jx1_Lbjqa-ttFCQgK-PA"

question = input("Ask something: ")

response = llm.invoke(question)
answer = response.content

if isinstance(answer, list):
    answer = "\n".join(
        item["text"]
        for item in answer
        if isinstance(item, dict) and item.get("type") == "text"
    )

print("\n" + "=" * 60)
print(question)
print("=" * 60)
print(answer)
print("=" * 60)

! pip install pypdf

import gradio as gr
from pypdf import PdfReader

from langchain_google_genai import ChatGoogleGenerativeAI


# -----------------------------
# 1. Read restaurant PDF
# -----------------------------

reader = PdfReader("Resturaunt Q&A.pdf")

restaurant_info = ""

for page in reader.pages:
    text = page.extract_text()

    if text:
        restaurant_info += text + "\n"


# -----------------------------
# 2. Create Gemini model
# -----------------------------

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    temperature=0
)


# -----------------------------
# 3. Chatbot
# -----------------------------

def chatbot(message, history):

    prompt = f"""
You are a restaurant customer support assistant.

Use the following restaurant information
to answer the customer's question.

Restaurant Information:
{restaurant_info}

Customer Question:
{message}

Answer the customer clearly and politely.
If the information is not available in the
restaurant information, say that you don't
have that information.
"""

    response = llm.invoke(prompt)

    return response.content


# -----------------------------
# 4. Gradio UI
# -----------------------------

demo = gr.ChatInterface(
    fn=chatbot,
    title="Restaurant Support Bot",
    description="Ask questions about our restaurant"
)

demo.launch()

from langchain_community.document_loaders import PyPDFLoader
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.agents import create_agent

# 1. Load PDF
loader = PyPDFLoader("/content/Ashwikha_20Revised.pdf")
documents = loader.load()

from langchain.tools import tool

# 2. Create a simple tool for the agent
@tool
def read_pdf(question: str) -> str:
    """Answer a question using the PDF content."""

    text = "\n".join(doc.page_content for doc in documents)

    return texts

# 4. Create Agent
agent = create_agent(
    model=llm,
    tools=[read_pdf],
    system_prompt="""
    You are a PDF reader agent.
    Use the read_pdf tool to find information from the PDF.
    Answer only using information from the PDF.
    If the answer is not available in the PDF, say:
    'I could not find this information in the PDF.'
    """
)

# 5. Ask a question
question = input("Ask something about the PDF: ")

result = agent.invoke({
    "messages": [
        {"role": "user", "content": question}
    ]
})

# Get final answer
answer = result["messages"][-1].content

# If Gemini returns a list, extract the text
if isinstance(answer, list):
    answer = "\n".join(
        item["text"]
        for item in answer
        if isinstance(item, dict) and item.get("type") == "text"
    )

print("\n" + "=" * 60)
print("🤖 PDF AGENT ANSWER")
print("=" * 60)
print(answer)
print("=" * 60)

"""Calculator tool"""

from langchain_core.tools import tool

@tool
def calculator(expression: str) -> str:
    """
    Calculate a mathematical expression.
    Use this tool when the user asks for a mathematical calculation.
    """

    try:
        result = eval(expression)
        return str(result)

    except Exception as e:
        return f"Calculation error: {e}"

"""tools"""

from langchain_core.tools import tool

@tool
def get_student(student_id: str) -> str:
    """Get student details using student ID."""
    return f"Student details retrieved for ID: {student_id}"

from langchain_core.tools import tool
@tool
def check_eligibility(student_id: str, company: str) -> str:
    """Check whether a student is eligible for a company."""
    return f"Eligibility checked for student {student_id} for {company}"


tools = [get_student, check_eligibility]