# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGaFd8IT5sl0qndfxfwFGGnPEkvOi7Ws
"""

pip install langgraph

from typing import TypedDict
from langgraph.graph import StateGraph,START,END

!pip install langchain langchain-community langchain-google-genai

import os
# google AI studio
os.environ["GOOGLE_API_KEY"] = "AQ.Ab8RN6Is_msKMW_uW6oMB96sCa9xfFpaOmS9iSnRpBvgrVdzeA"

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-3.5-flash-lite",
    temperature=0
)

from typing import TypedDict
from langgraph.graph import StateGraph,START,END

#state definition

class State(TypedDict):
  name: str
  message: str
  question: str

#Node definition

def greeting_node(state: State):
  return{
      "message" : f"Hello {state['name']}"
  }

#create graph

graph = StateGraph(State)

#add node

graph.add_node("greeting",greeting_node)

#add edges

graph.add_edge(START,"greeting")
graph.add_edge("greeting",END)

#define newnode

def newnode_node(state: State):
  return{
      "message" : f"Hello {state['name']}"
  }

#define graph

graph = StateGraph(State)

#add node

graph.add_node("greeting",greeting_node)
graph.add_node("newnode",newnode_node)

#add edges

graph.add_edge(START,"greeting")
graph.add_edge("greeting","newnode")
graph.add_edge("newnode",END)

#compile
app=graph.compile()

question=input("Enter your name:")
response=app.invoke({"name":question})
print(response)

#state definition

class State(TypedDict):
  name: str
  message: str
  question: str

#create llm node

def llm_node(state: State):
  response=llm.invoke(
      state["question"]
  )

  return{
      "message": response.content
  }

#build graph

graph=StateGraph(State)

#create node

graph.add_node("llm",llm_node)

#create edges

graph.add_edge(START,'llm')
graph.add_edge('llm',END)

app=graph.compile()

name=input("Enter name: ")
answer=app.invoke({
    "question":name
})

print(answer)

"""Tools and LLMs"""

from typing_extensions import TypedDict

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.tools import tool
from langchain_core.messages import ToolMessage
from langgraph.graph import StateGraph, START, END

#tools

@tool
def add(a:int,b:int)->int:
  """Adding 2 numbers"""
  return a+b

@tool
def multiply(a:int,b:int)->int:
  """Multiplying 2 numbers"""
  return a*b

@tool
def divide(a:int,b:int)->float:
  """Dividing 2 numbers"""
  return a/b

tools = [add, multiply, divide]

tools_by_name = {
    tool.name: tool
    for tool in tools
}

#tools_by_name = {
    # "addition": addition,
    # "multiply": multiplication,
    # "divice" : division}

#LLM

model = ChatGoogleGenerativeAI(
    model="gemini-3.5-flash-lite",
    temperature=0
)

model_with_tools = model.bind_tools(tools)

#state

class State(TypedDict):
    messages: list

#llm node

def llm_call(state):

    response = model_with_tools.invoke(
        state["messages"]
    )

    return {
        "messages": [response]
    }

#tool node

def tool_node(state):

    results = []

    last_message = state["messages"][-1]

    for tool_call in last_message.tool_calls:

        tool_name = tool_call["name"]

        tool_args = tool_call["args"]

        tool = tools_by_name[tool_name]

        result = tool.invoke(tool_args)

        results.append(
            ToolMessage(
                content=str(result),
                tool_call_id=tool_call["id"]
            )
        )

    return {
        "messages": results
    }

#routing

def should_continue(state):

    last_message = state["messages"][-1]

    if last_message.tool_calls:
        return "tool_node"

    return "end"

"""llm-->tool(+,*,/)-->yes
   -->tool-->no
"""

#build graph

builder = StateGraph(State)

builder.add_node("llm_call", llm_call)

builder.add_node("tool_node", tool_node)

builder.add_edge(
    START,
    "llm_call"
)

builder.add_conditional_edges(
    "llm_call",
    should_continue,
    {
        "tool_node": "tool_node",
        "end": END
    }
)

builder.add_edge(
    "tool_node",
    "llm_call"
)


agent = builder.compile()

#run

question = input(
    "Enter your calculation: "
)

result = agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    }
)

print("\nAgent response:")

print(
    result["messages"][-1].content
)

input("\nPress Enter to exit...")